### ISSUE TITLE
Line breaks are removed from a secret when accessed in a Cloud Build workflow

### ISSUE THREAD

**Issue by femtozer** [GoogleCloudPlatform/cloud-build-samples#121]
I don't know if this is the right repo to open this issue.
I use Cloud Build to deploy my webapp to App Engine.
I'm storing the config file of the app (.env) in a Secret Manager secret.
In the workflow, the value of the secret in a file before the App Engine deploy.
The line breaks are removed, causing the app to not read correctly the config file.
The only workaround I found is to encode the secret in base64 and to decode it at build time, but this makes the process more complex...

``` yaml
  - id: set-env
    name: gcr.io/cloud-builders/docker
    entrypoint: bash
    args:
      - -c
      - echo $$APP_CONFIG | base64 --decode > .env
    secretEnv: ["APP_CONFIG"]
```

When I use the gcloud command line to get the value of the secret, the line breaks are not removed.

**Comment by rogerthatdev** [comment]
Hi, thanks for opening this issue!

I was able to duplicate this behavior. The missing line breaks are due to the `echo` command's behavior.

Adding quotes `" "` around `$$APP_CONFIG` will preserve the line breaks without having to encode or decode. 

Try:

```
  - id: set-env
    name: gcr.io/cloud-builders/docker
    entrypoint: bash
    args:
      - -c
      - echo "$$APP_CONFIG" > .env
    secretEnv: ["APP_CONFIG"]
```
I will close this issue, but please do not hesitate to reopen if you have additional questions, or if this solution does not work for you.

Thanks!
